"""create tables

Revision ID: 6338a6598c98
Revises: fe2fef2ddba0
Create Date: 2025-08-01 18:05:37.092535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6338a6598c98'
down_revision: Union[str, Sequence[str], None] = 'fe2fef2ddba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blogs', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'owner_id')
    # ### end Alembic commands ###
